# Data Science: Bridging Principles and Practice
## Part 10: Rocket Fuel Costs, Benefits, and Efficacy

<img src="assets/berkeley_img-4-1.jpg" style="width: 700px; height: 300px;" />

*In this notebook, we will apply what we learned about Python and dataframes to compute the costs, benefits, and return on investment for the Rocket Fuel handbag case study.*

### Table of Contents


<ol start=10><li><a href='#section10'>Problem: Rocket Fuel Costs, Benefits, and Efficacy</a></li>
    <ol>
     <li><a href='#section10a'>Conversion Proportions</a></li>
     <li><a href='#section10b'>Benefit</a></li>
     <li><a href='#section10c'>ROI</a></li>
     <li><a href='#section10d'>Opportunity Cost</a></li>
     </ol>
    </ol>
    
    
As usual, we begin by importing the necessery libraries.

In [1]:
# load the necessary software. THIS CELL MUST BE RUN
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Rocket Fuel Ad Campaign <a id='section case'></a>
### (Review from notebooks 03, 04, and 05)

[Rocket Fuel Inc.](https://rocketfuel.com/programmatic-marketing-platform/) (NASDAQ: FUEL), works in digital advertising offering a "Programmatic Marketing Platform" that claims to optimize digital marketing through big data and machine learning techniques.

In 2015, Rocket Fuel ran a trial ad campaign for handbag manufacturer TaskBella. TaskBella was interested in answering two questions:

1. Would the campaign be successful?
2. If the campaign was successful, how much of that success could be attributed to the ads?

With the second question in mind, they agreed to run an **A/B test**. The majority of the people exposed to Rocket Fuel's content delivery network would see TaskBella's handbag ad (the **experimental group**). But, a small portion of people (the **control group**) would instead see a Public Service Announcement (PSA) in the exact size and place the ad would normally be. One PSA example is below:

<img src="assets/smokey_bear_psa.PNG" style="width: 700px; height: 300px;" />

## 10. Problem: Rocket Fuel Costs, Benefits, and Efficacy <a id='section10'></a>

Earlier in the course we explored the Rocket Fuel study in terms of grouping and visualizing the data. Now, we want to see whether or not the campaign worked.

In this section, we'll explore four questions:

> * *Was the campaign effective? Did more users convert as a result of seeing an ad?*
> * *How much more money did TaskBella make as a result of running the campaign (ignoring advertising costs)?*
> * *Was the campaign profitable (what was the ROI)?*
> * *What was the opportunity cost of including a control group? How much more could have TaskBella made with a smaller control group or not having a control group at all?*

Run the next cell to load and visualize the data.

In [2]:
# run this cell to load the data
ads = pd.read_csv('data/rocketfuel_data_renamed.csv', index_col = 0)

# show the first five rows of the ads data
ads.head()

   user id test group  converted  total ads most ads day  most ads hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

Run the cell below to split the data into two smaller DataFrames: one that only has subjects in the control ("psa") group, and another that only has subject in the test ("ad") group.

In [3]:
# create a DataFrame with only users in the control (PSA) group
control = ads[ads["test group"] == "psa"]

# create a DataFrame with only users in the experimental (ad) group
experiment = ads[ads["test group"] == "ad"]
experiment.head()

   user id test group  converted  total ads most ads day  most ads hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

### 10a. Did more users convert as a result of the ad campaign? <a id='section10a'></a>

We're interested in seeing if the buying behavior of users differed between the control and experimental groups. The two groups are very different in size, so it isn't fair to compare the number of people who converted in each group. Instead, we're going to look at the *proportion* of people in each group who bought a bag.

For both groups, the proportion will be calculated as:
$$\frac{\text{number of people in group who converted}}{\text{total number of people in group}}$$

Let's start with the control group. To get the number of people in the control group, we can use the `shape` attribute to get the shape of the DataFrame.

In [4]:
control.shape

(23524, 6)

The `shape` attribute returns two values: the number of rows followed by the number of columns. We only want the number of rows (the first value), so we'll use indexing to get it. Remember that in Python indexing starts at 0.

In [5]:
# number of users in control group
num_control = control.shape[0]
num_control

23524

Next, we need a table with only users in the control group who converted. We can get this using Boolean indexing. Our condition inside the square brackets (i.e. how we want to select the rows) is that we want rows where the "converted" feature is `True`.

In [6]:
# table with only converting control group users
ctrl_converts = control[control["converted"] == True]
ctrl_converts.head()

      user id test group  converted  total ads most ads day  most ads hour
957    915026        psa       True         88       Sunday             19
2531   904434        psa       True          7      Tuesday             20
2744   920737        psa       True         77       Monday             13
2751   904131        psa       True        111       Monday             12
2979   901749        psa       True        364       Friday             21

From this new table, we can get the number of converting control group users by again using `shape`.

In [7]:
# number of people in the ctrl_converts table
num_ctrl_converts = ctrl_converts.shape[0]
num_ctrl_converts

420

Finally, we can plug the number of control group converts and the total number of control group people into our formula to find the percentage.

In [8]:
# proportion of control group users who converted
ctrl_convert_proportion = (num_ctrl_converts / num_control)
ctrl_convert_proportion

0.01785410644448223

<div class="alert alert-warning"><p><b>EXERCISE:</b>
    
Find the proportion of people in the <b>experiment</b> group who converted. You can follow the exact same steps as we did above for the control group; in all steps the code will be identical except for the variable and table names.</p>

<p>Step 1: Get the number of people in the experiment group using the <code>experiment</code> table, the <code>shape</code> attribute, and indexing. Assign the result as an integer to <code>num_exper</code>.</p>
</div>

In [9]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
num_exper = experiment.shape[0]

# YOUR CODE HERE
# raise NotImplementedError()

# number of people in the experiment (ad) group
num_exper

564577

<div class="alert alert-warning"><p><b>EXERCISE:</b>
    
Step 2: Use boolean indexing to create a dataframe with only <b>users in the experiment group who converted</b>. Assign your result to `exper_converts`.</p>
    
<p> Hint: if you're stuck, look at how we did it for the control group. It's the same task, so the code will look very similar, but all references to the <code>control</code> dataframe will be replaced by the <code>experiment</code> dataframe.
</div>

In [10]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
exper_converts = experiment[experiment["converted"] == True]

# YOUR CODE HERE
# raise NotImplementedError()
# get only the experiment group users who converted
exper_converts.head()

     user id test group  converted  total ads most ads day  most ads hour
15   1461774         ad       True          9    Wednesday             18
44   1355531         ad       True        265      Tuesday             12
107  1389878         ad       True       1328     Saturday             19
121  1475989         ad       True        323     Saturday             20
135  1241733         ad       True        246       Friday             20

<div class="alert alert-warning"><p><b>EXERCISE:</b>
    
Step 3: Get the number of converted experiment group users using the table you just created, the <code>shape</code> attribute, and indexing. Assign the result to the variable <code>num_exper_converts</code>.
</div>

In [11]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
num_exper_converts = exper_converts.shape[0]

# YOUR CODE HERE
# raise NotImplementedError()
# count the number of converting experimental group members
num_exper_converts

14423

<div class="alert alert-warning"><p><b>EXERCISE:</b>
    
Step 4: Plug the values from step 1 and step 3 into the formula to calculate the proportion.</p>
<br>
$$\frac{\text{number of people in group who converted}}{\text{total number of people in group}}$$
<br>
    
Assign the result to the variable <code>exper_convert_proportion</code>.
    
<p>Hint: you don't have to type any numbers here; use the names of the two variables you just created.
</div>

In [14]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
exper_convert_proportion  = num_exper_converts / num_exper

# YOUR CODE HERE
# raise NotImplementedError()
# the proportion of people in the experimental group that converted
exper_convert_proportion

0.025546559636683747

The next cell will print the values you calculated as percents of the control and experiment groups that converted, rounded to two decimal places.

In [15]:
print("Control Group: {} % converted".format(round(ctrl_convert_proportion * 100, 2))) 
print("Experiment Group: {} % converted".format(round(exper_convert_proportion * 100, 2)))

Control Group: 1.79 % converted
Experiment Group: 2.55 % converted

<div class="alert alert-warning"><b>QUESTION:</b> 
    
Is the following statement true or false?
    
A user who saw the ad was more likely to buy a bag than a user who didn't see the ad.

Assign your response as a Boolean (<code>True</code> or <code>False</code>) to the variable `str_1`.
    </div>

In [16]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
str_1  = True

# YOUR CODE HERE
# raise NotImplementedError()

### 10b. How much more money did TaskBella make as a result of running the campaign (ignoring advertising costs)? <a id='section10b'></a>

Here we're looking for the benefit of the campaign: the expected financial impact from the conversions resulting from the ads (excluding all advertising costs).

The formula for the benefit is as follows:

$$ (\text{value of a converted user}) * (\text{number of users in the experiment group}) * (\text{proportion of converting experiment group users} - \text{proportion of converting control group users}) $$

That is, we are looking for the number of people in the experiment group who bought a handbag and *wouldn't have bought one if they'd been in the control group*. This is why we subtract the control group conversion percentage from the experiment group conversion percentage.

We already have most of the parts of this formula- we just need to assemble them.

<div class="alert alert-warning"><b> EXERCISE:</b>
    
TaskBella estimates the value of a converted user to be $\$40$. In the following cell, assign <code>40</code> to the name <code>convert_val</code>.
</div>

In [19]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
convert_val  = 40

# YOUR CODE HERE
# raise NotImplementedError()

<div class="alert alert-warning"><b> EXERCISE:</b>
   
Compute the difference in conversion proportions for the experiment and control groups: <br>
<br>
$$\text{proportion of converting experiment group users} - \text{proportion of converting control group users}$$
<br>
Assign the result to <code>proportion_diff</code>.
</div>

In [20]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
proportion_diff  = exper_convert_proportion - ctrl_convert_proportion

# YOUR CODE HERE
# raise NotImplementedError()
# the difference between the experiment conversion proportion and the control conversion proportion
proportion_diff

0.007692453192201517

<div class="alert alert-warning"><b> EXERCISE:</b>
   
Lastly, plug all the appropriate values into the benefit formula to get the benefit.
<br>
$$ (\text{value of a converted user}) * (\text{number of users in the experiment group}) * (\text{proportion of converting experiment group users} - \text{proportion of converting control group users}) $$
<br>


Assign the result to the variable <code>benefit</code>.

Hint: the number of users in the experiment group is saved as <code>num_exper</code>.

In [21]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
benefit = 173719.28583574222

# YOUR CODE HERE
# raise NotImplementedError()
benefit

173719.28583574222

### 10c. What was the Return on Investment (ROI)? <a id='section10c'></a>

In parts 10a and 10b we saw that advertising resulted in a higher percentage of converting users and a positive benefit. But, would using the campaign still increase profits when advertising costs are accounted for?

Recall that back in Notebook 02 we calculated the advertising costs and named them `cost`. Run the next cell to re-define that variable with the cost we calculated.

In [22]:
# the cost of the campaign
cost = 131374.64

<div class="alert alert-warning"><b>EXERCISE:</b> Calculate the ROI as 

$$\frac{\text{benefit} - \text{cost}}{\text{cost}}$$
    
Assign the result to the variable <code>roi</code>.
</div>

In [23]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
roi = 0.32231978588669935

# YOUR CODE HERE
# raise NotImplementedError()
roi

0.32231978588669935

### 10d. What was the opportunity cost of including a control group? <a id='section10d'></a>

As we saw in 10b, having a control group is important to get a baseline to compare the experimental data with. However, any user assigned to the control group are not seeing TaskBella's advertising, eating into profits.

We can calculate the *opportunity cost* of the control group as:

$$(\text{value of converted user}) * (\text{number of users in control group}) * (\text{proportion of experiment group users who converted} - \text{proportion of control group users who converted})$$

In other words, the opportunity cost is the additional amount of money users in the control group would have spent if they had seen the ads *purely as a result of seeing the ads*. Note that this is almost the same formula as for the benefit in 10b, except with the control group instead of the experiment group.

<div class="alert alert-warning"><b>EXERCISE:</b> Use <code>convert_val</code>, <code>num_control</code>, and <code>proportion_diff</code> to calculate the opportunity cost.

Assign the result to the variable <code>opp_cost</code>.</div>

In [24]:
### GRADED
### YOUR ANSWER BELOW

### YOUR SOLUTION HERE
opp_cost = 7238.2907557339395

# YOUR CODE HERE
# raise NotImplementedError()
opp_cost

7238.2907557339395

#### References

- Rocket Fuel data and discussion questions adapted from materials by Zsolt Katona and Brian Bell, BerkeleyHaas Case Series

Author: Keeley Takimoto